interface PropertyInterface {
  id: string;
  name: string;
  location: string;
  country: string;
  description:string;
  option:string;
  category:string;
  price:number;
  images?:{
    thumbnail?:string; 
    banner?:string;
    banner2?:string
  },
liked:boolean,
  specifications: {
    room: number;
    bathRoom: number;
    area: number;
    condition: boolean;
  };
}
const properties = [
  {
    id: "in7523",
    name: "Spacious Family Villa",
    location: "45 Garden Avenue, Mumbai, India",
    country: "India",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
    description: "Charming and spacious family villa located in a peaceful neighborhood. This beautiful property features five bedrooms, three bathrooms, and a large living area, making it perfect for a growing family. The villa comes with modern amenities and a well-maintained garden, providing a serene retreat in the bustling city. Conveniently located close to schools, parks, and shopping centers.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Villa",
    price: 750000,
  },
  {
    id: "us8416",
    name: "Contemporary Townhome",
    location: "25 Oak Street, New York, USA",
    country: "United States",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1500,
      condition: true,
    },
    description: "Modern and stylish townhome in the heart of New York City. This contemporary property features three bedrooms, two bathrooms, and an open-concept living space with high-end finishes. Enjoy the convenience of city living with easy access to restaurants, shops, and cultural attractions.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Townhome",
    price: 3500,
  },
  {
    id: "jp6128",
    name: "Traditional Machiya",
    location: "8 Hanamikoji Street, Kyoto, Japan",
    country: "Japan",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
    description: "Experience the charm of traditional Japanese living in this classic Machiya townhouse. The property features four bedrooms, two bathrooms, and elegant wooden interiors. Embrace the cultural heritage and serenity of Kyoto while being close to popular attractions and historic landmarks.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: true,
    category: "Machiya",
    price: 2000,
  },
  {
    id: "be1235",
    name: "Elegant City Apartment",
    location: "5 Rue Royale, Brussels, Belgium",
    country: "Belgium",
    specifications: {
      room: 2,
      bathRoom: 1,
      area: 1000,
      condition: true,
    },
    description: "Stylish and elegant apartment located in the heart of Brussels. This two-bedroom property features modern design and offers a comfortable living space. Enjoy the convenience of city living with easy access to restaurants, shops, and cultural landmarks. Ideal for young professionals and couples seeking a contemporary urban lifestyle.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "Apartment",
    price: 350000,
  },
  {
    id: "ca4357",
    name: "Luxurious Beachfront Villa",
    location: "30 Ocean Drive, Vancouver, Canada",
    country: "Canada",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 3500,
      condition: true,
    },
    description: "Indulge in luxury with this breathtaking beachfront villa in Vancouver. This six-bedroom property offers stunning ocean views, high-end amenities, and a private beach access. Relax in the lap of luxury while enjoying the tranquility of the sea. Perfect for those seeking an exclusive coastal retreat.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Villa",
    price: 2200000,
  },
  {
    id: "pk9205",
    name: "Scenic Hillside Retreat",
    location: "55 Mountain View Road, Islamabad, Pakistan",
    country: "Pakistan",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 2000,
      condition: true,
    },
    description: "Escape to nature with this hillside retreat in Islamabad. Surrounded by lush greenery, this three-bedroom property offers breathtaking views and a serene atmosphere. Embrace the tranquility of the mountains while still being close to city amenities. Ideal for nature lovers and those seeking a peaceful haven.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Retreat",
    price: 1200,
  },
  {
    id: "it5368",
    name: "Rustic Tuscan Farmhouse",
    location: "78 Olive Grove, Tuscany, Italy",
    country: "Italy",
    specifications: {
      room: 7,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
    description: "Experience the charm of Tuscany with this rustic farmhouse nestled amidst olive groves. The property boasts seven bedrooms, three bathrooms, and classic Tuscan architecture. Enjoy the tranquility of the countryside while still being close to cultural attractions and vineyards. Ideal for those seeking an authentic Tuscan experience.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Farmhouse",
    price: 890000,
  },
  {
    id: "de4926",
    name: "Country Cottage",
    location: "20 Meadow Lane, Munich, Germany",
    country: "Germany",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1200,
      condition: true,
    },
    description: "Escape to the German countryside with this charming country cottage. The property features three bedrooms, two bathrooms, and a cozy living area with traditional design. Embrace the serenity of nature while still being close to city amenities. Ideal for those seeking a peaceful retreat away from the hustle and bustle.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Cottage",
    price: 1800,
  },
  {
    id: "us6214",
    name: "Urban Studio Loft",
    location: "7 Loft Avenue, Chicago, USA",
    country: "United States",
    specifications: {
      room: 1,
      bathRoom: 1,
      area: 750,
      condition: true,
    },
    description: "Live in style with this chic urban studio loft in the heart of Chicago. This modern property offers one bedroom, one bathroom, and an open living space with industrial design. Enjoy the vibrant city life with easy access to restaurants, cafes, and cultural events. Ideal for young professionals and creatives seeking a trendy urban living space.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: true,
    category: "Loft",
    price: 2000,
  },
  {
    id: "jp3509",
    name: "Zen Garden House",
    location: "15 Bamboo Grove, Tokyo, Japan",
    country: "Japan",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2200,
      condition: true,
    },
    description: "Find inner peace with this Zen garden house in the heart of Tokyo. This five-bedroom property offers a tranquil atmosphere with a traditional Japanese garden. Embrace the harmony of nature while still being close to the city's bustling energy. Ideal for those seeking a balance between modern living and Zen serenity.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "House",
    price: 1850000,
  },
  {
    id: "ca3298",
    name: "Charming Log Cabin",
    location: "40 Pine Trail, Calgary, Canada",
    country: "Canada",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
    description: "Experience rustic charm with this charming log cabin in Calgary. The property offers four bedrooms, two bathrooms, and a cozy living space with a wood-burning fireplace. Embrace the natural beauty of the surrounding pine trees while still being close to city amenities. Ideal for those seeking a cozy and intimate living space.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: true,
    category: "Log Cabin",
    price: 1500,
  },
  {
    id: "in2714",
    name: "City High-Rise Apartment",
    location: "25 Skyscraper Avenue, Bangalore, India",
    country: "India",
    specifications: {
      room: 2,
      bathRoom: 2,
      area: 1100,
      condition: true,
    },
    description: "Live in the clouds with this city high-rise apartment in Bangalore. This two-bedroom property offers stunning views of the city skyline and modern amenities. Experience the excitement of urban living with easy access to restaurants, shopping malls, and entertainment. Ideal for young professionals and couples seeking a sophisticated city lifestyle.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "Apartment",
    price: 450000,
  },
  {
    id: "be5831",
    name: "Historic Castle",
    location: "10 Royal Street, Brussels, Belgium",
    country: "Belgium",
    specifications: {
      room: 10,
      bathRoom: 5,
      area: 6000,
      condition: true,
    },
    description: "Live like royalty with this historic castle in Brussels. This grand property offers ten bedrooms, five bathrooms, and majestic architecture with rich history. Embrace the grandeur of the past while enjoying modern comforts and amenities. Ideal for those seeking an extraordinary and unique living experience in a castle setting.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Castle",
    price: 4000000,
  },
  {
    id: "ca5291",
    name: "Ski Resort Chalet",
    location: "65 Snowy Lane, Whistler, Canada",
    country: "Canada",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 3200,
      condition: true,
    },
    description: "Embrace the winter wonderland with this ski resort chalet in Whistler. This six-bedroom property offers a cozy retreat with stunning mountain views. Enjoy the convenience of ski-in/ski-out access and proximity to the ski resort. Ideal for ski enthusiasts and nature lovers seeking a mountain getaway.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Chalet",
    price: 3000,
  },
  {
    id: "pk9514",
    name: "Modern City Apartment",
    location: "40 Downtown Avenue, Karachi, Pakistan",
    country: "Pakistan",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1200,
      condition: true,
    },
    description: "Experience contemporary city living with this modern apartment in Karachi. The property features three bedrooms, two bathrooms, and a stylish living space with modern finishes. Enjoy the convenience of city amenities, restaurants, and shopping centers at your doorstep. Ideal for those seeking a trendy and vibrant urban lifestyle.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Apartment",
    price: 180000,
  },
  {
    id: "it3687",
    name: "Seaside Villa",
    location: "20 Coastal Road, Amalfi, Italy",
    country: "Italy",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 1800,
      condition: true,
    },
    description: "Escape to the Amalfi Coast with this stunning seaside villa. The property offers four bedrooms, three bathrooms, and breathtaking views of the Mediterranean Sea. Relax in the private garden or take a short walk to the beach. Ideal for those seeking a luxurious coastal retreat with Italian charm.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Villa",
    price: 5000,
  },
  {
    id: "de1742",
    name: "Green Countryside Retreat",
    location: "33 Meadow Path, Hamburg, Germany",
    country: "Germany",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2500,
      condition: false,
    },
    description: "Embrace the beauty of nature with this green countryside retreat in Hamburg. This five-bedroom property offers a tranquil atmosphere and scenic views of meadows and forests. Enjoy the serenity of the countryside while still being close to city amenities. Ideal for those seeking a peaceful escape in nature's embrace.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Retreat",
    price: 1400000,
  },
  {
    id: "us7459",
    name: "Luxury Beach House",
    location: "15 Shoreline Drive, Malibu, USA",
    country: "United States",
    specifications: {
      room: 8,
      bathRoom: 4,
      area: 4000,
      condition: true,
    },
    description: "Indulge in luxury with this beachfront paradise in Malibu. This eight-bedroom property offers direct access to the beach and panoramic ocean views. Relax in the infinity pool or take a stroll along the sandy shores. Ideal for those seeking a luxurious beachfront lifestyle with privacy and exclusivity.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Beach House",
    price: 7000000,
  },
  {
    id: "jp2851",
    name: "Traditional Machiya",
    location: "8 Hanamikoji Street, Kyoto, Japan",
    country: "Japan",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
    description: "Experience the charm of traditional Japanese living in this classic Machiya townhouse. The property features four bedrooms, two bathrooms, and elegant wooden interiors. Embrace the cultural heritage and serenity of Kyoto while being close to popular attractions and historic landmarks.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: true,
    category: "Machiya",
    price: 2200,
  },
  {
    id: "hf4353",
    name: "Venice Mansion Exclusive",
    location: "225 b baker street Venice, Italy",
    country: "Italy",
    specifications: {
      room: 8,
      bathRoom: 4,
      area: 1800,
      condition: true,
    },
    description: "Step into a world of opulence with this exclusive mansion in Venice. This eight-bedroom property features stunning architecture, luxurious interiors, and views of the iconic canals. Live in grandeur and sophistication in the heart of Venice. Ideal for those seeking an extraordinary and prestigious living experience.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "Mansion",
    price: 10000000,
  },
  {
    id: "gk9821",
    name: "Luxury Villa Retreat",
    location: "Sunset Boulevard, Los Angeles, USA",
    country: "United States",
    specifications: {
      room: 12,
      bathRoom: 6,
      area: 5000,
      condition: true,
    },
    description: "Escape to the lap of luxury with this exclusive villa retreat in Los Angeles. This twelve-bedroom property offers breathtaking views, a private pool, and high-end amenities. Enjoy the serenity of the Hollywood Hills while still being close to the city's entertainment and cultural scene. Ideal for celebrities and those seeking an extraordinary living experience.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Villa",
    price: 15000000,
  },
  {
    id: "bh7832",
    name: "Mountain Cabin Getaway",
    location: "100 Pine Trail, Banff, Canada",
    country: "Canada",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2000,
      condition: true,
    },
    description: "Experience the beauty of the Canadian Rockies with this mountain cabin getaway in Banff. The property features five bedrooms, three bathrooms, and stunning views of the surrounding peaks. Enjoy outdoor adventures and the beauty of nature while still being close to town amenities. Ideal for those seeking a cozy mountain retreat.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: false,
    category: "Cabin",
    price: 2500,
  },
  {
    id: "ja9102",
    name: "Coastal Retreat",
    location: "123 Beachfront Drive, Bali, Indonesia",
    country: "Indonesia",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 2200,
      condition: true,
    },
    description: "Escape to the beautiful island of Bali with this coastal retreat. The property offers four bedrooms, three bathrooms, and breathtaking views of the Indian Ocean. Relax in the private infinity pool or take a short walk to the sandy beach. Ideal for those seeking a tropical paradise and a tranquil living experience.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: true,
    category: "Retreat",
    price: 4000000,
  },
  {
    id: "fr5763",
    name: "Château de Versailles",
    location: "1 Royal Palace, Versailles, France",
    country: "France",
    specifications: {
      room: 30,
      bathRoom: 15,
      area: 10000,
      condition: true,
    },
    description: "Step into history with this majestic château in Versailles. The property offers thirty bedrooms, fifteen bathrooms, and opulent interiors fit for royalty. Embrace the grandeur of the past while enjoying modern luxuries and amenities. Ideal for those seeking an extraordinary living experience in a historic setting.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "Château",
    price: 50000000,
  },
  {
    id: "sp6281",
    name: "Spanish Villa",
    location: "25 Costa del Sol, Marbella, Spain",
    country: "Spain",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 3000,
      condition: true,
    },
    description: "Embrace the Mediterranean lifestyle with this Spanish villa in Marbella. This six-bedroom property offers a private garden, swimming pool, and views of the coastline. Enjoy the vibrant Spanish culture, sandy beaches, and golf courses nearby. Ideal for those seeking a luxurious and relaxed living experience on the Costa del Sol.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Rent",
    liked: true,
    category: "Villa",
    price: 6000,
  },
  {
    id: "au9274",
    name: "Modern Waterfront House",
    location: "10 Bayview Drive, Sydney, Australia",
    country: "Australia",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
    description: "Experience waterfront living with this modern house in Sydney. The property features four bedrooms, three bathrooms, and stunning views of the bay. Enjoy the tranquil waterfront lifestyle while still being close to the city's attractions and amenities. Ideal for those seeking a contemporary living experience with a touch of nature's beauty.",
    images: {
      thumbnail: "path-to-thumbnail-image",
      banner: "path-to-banner-image",
      banner2: "path-to-banner2-image",
    },
    option: "For Sale",
    liked: false,
    category: "House",
    price: 3800000,
  }
];


