interface PropertyInterface {
  id: string;
  name: string;
  location: string;
  country: string;
  specifications: {
    room: number;
    bathRoom: number;
    area: number;
    condition: boolean;
  }
}

export const dataArray: PropertyInterface[] = [
  {
    id: "ch2301",
    name: "Modern Loft Apartment",
    location: "10 Urban Street, Berlin, Germany",
    country: "Germany",
    specifications: {
      room: 2,
      bathRoom: 1,
      area: 900,
      condition: true,
    },
  },
  {
    id: "in7523",
    name: "Spacious Family Villa",
    location: "45 Garden Avenue, Mumbai, India",
    country: "India",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
  },
  {
    id: "us8416",
    name: "Contemporary Townhome",
    location: "25 Oak Street, New York, USA",
    country: "United States",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1500,
      condition: true,
    },
  },
  {
    id: "jp6128",
    name: "Traditional Machiya",
    location: "8 Hanamikoji Street, Kyoto, Japan",
    country: "Japan",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "be1235",
    name: "Elegant City Apartment",
    location: "5 Rue Royale, Brussels, Belgium",
    country: "Belgium",
    specifications: {
      room: 2,
      bathRoom: 1,
      area: 1000,
      condition: true,
    },
  },
  {
    id: "ca4357",
    name: "Luxurious Beachfront Villa",
    location: "30 Ocean Drive, Vancouver, Canada",
    country: "Canada",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 3500,
      condition: true,
    },
  },
  {
    id: "pk9205",
    name: "Scenic Hillside Retreat",
    location: "55 Mountain View Road, Islamabad, Pakistan",
    country: "Pakistan",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 2000,
      condition: true,
    },
  },
  {
    id: "it5368",
    name: "Rustic Tuscan Farmhouse",
    location: "78 Olive Grove, Tuscany, Italy",
    country: "Italy",
    specifications: {
      room: 7,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
  },
  {
    id: "de4926",
    name: "Country Cottage",
    location: "20 Meadow Lane, Munich, Germany",
    country: "Germany",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1200,
      condition: true,
    },
  },
  {
    id: "us6214",
    name: "Urban Studio Loft",
    location: "7 Loft Avenue, Chicago, USA",
    country: "United States",
    specifications: {
      room: 1,
      bathRoom: 1,
      area: 750,
      condition: true,
    },
  },
  {
    id: "jp3509",
    name: "Zen Garden House",
    location: "15 Bamboo Grove, Tokyo, Japan",
    country: "Japan",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2200,
      condition: true,
    },
  },
  {
    id: "ca3298",
    name: "Charming Log Cabin",
    location: "40 Pine Trail, Calgary, Canada",
    country: "Canada",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "in2714",
    name: "City High-Rise Apartment",
    location: "25 Skyscraper Avenue, Bangalore, India",
    country: "India",
    specifications: {
      room: 2,
      bathRoom: 2,
      area: 1100,
      condition: true,
    },
  },
  {
    id: "be5831",
    name: "Historic Castle",
    location: "10 Royal Street, Brussels, Belgium",
    country: "Belgium",
    specifications: {
      room: 10,
      bathRoom: 5,
      area: 6000,
      condition: true,
    },
  },
  {
    id: "ca5291",
    name: "Ski Resort Chalet",
    location: "65 Snowy Lane, Whistler, Canada",
    country: "Canada",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 3200,
      condition: true,
    },
  },
  {
    id: "pk9514",
    name: "Modern City Apartment",
    location: "40 Downtown Avenue, Karachi, Pakistan",
    country: "Pakistan",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1200,
      condition: true,
    },
  },
  {
    id: "it3687",
    name: "Seaside Villa",
    location: "20 Coastal Road, Amalfi, Italy",
    country: "Italy",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 1800,
      condition: true,
    },
  },
  {
    id: "de1742",
    name: "Green Countryside Retreat",
    location: "33 Meadow Path, Hamburg, Germany",
    country: "Germany",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2500,
      condition: false,
    },
  },
  {
    id: "us7459",
    name: "Luxury Beach House",
    location: "15 Shoreline Drive, Malibu, USA",
    country: "United States",
    specifications: {
      room: 8,
      bathRoom: 4,
      area: 4000,
      condition: true,
    },
  },
  {
    id: "jp2851",
    name: "Traditional Machiya",
    location: "8 Hanamikoji Street, Kyoto, Japan",
    country: "Japan",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "hf4353",
    name: "Venice Mansion Exclusive",
    location: "225 b baker street Venice, Italy",
    country: "Italy",
    specifications: {
      room: 8,
      bathRoom: 4,
      area: 1800,
      condition: true,
    },
  },
  {
    id: "gk9821",
    name: "Luxury Villa Retreat",
    location: "Sunset Boulevard, Los Angeles, USA",
    country: "United States",
    specifications: {
      room: 12,
      bathRoom: 6,
      area: 5000,
      condition: true,
    },
  },
  {
    id: "bh7832",
    name: "Mountain Cabin Getaway",
    location: "100 Pine Trail, Banff, Canada",
    country: "Canada",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2000,
      condition: true,
    },
  },
  {
    id: "ja9102",
    name: "Coastal Retreat",
    location: "123 Beachfront Drive, Bali, Indonesia",
    country: "Indonesia",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 2200,
      condition: true,
    },
  },
  {
    id: "df3178",
    name: "Spacious Family Home",
    location: "15 Maple Avenue, Toronto, Canada",
    country: "Canada",
    specifications: {
      room: 6,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
  },
  {
    id: "vc6254",
    name: "Contemporary Urban Loft",
    location: "7 Loft Street, New York, USA",
    country: "United States",
    specifications: {
      room: 1,
      bathRoom: 1,
      area: 1000,
      condition: true,
    },
  },
  {
    id: "wt8573",
    name: "Lakefront Retreat",
    location: "25 Lakeside Drive, Geneva, Switzerland",
    country: "Switzerland",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 2100,
      condition: true,
    },
  },
  {
    id: "ld6942",
    name: "Historic Townhouse",
    location: "21 Heritage Street, Rome, Italy",
    country: "Italy",
    specifications: {
      room: 9,
      bathRoom: 4,
      area: 2500,
      condition: false,
    },
  },
  {
    id: "gy5928",
    name: "Cozy Log Cabin",
    location: "50 Forest Trail, Oslo, Norway",
    country: "Norway",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "xt4267",
    name: "Urban Penthouse",
    location: "12 High Street, Tokyo, Japan",
    country: "Japan",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1500,
      condition: true,
    },
  },
  {
    id: "su1853",
    name: "City View Apartment",
    location: "40 Skyline Avenue, Dubai, UAE",
    country: "United Arab Emirates",
    specifications: {
      room: 2,
      bathRoom: 2,
      area: 1000,
      condition: true,
    },
  },
  {
    id: "cn8471",
    name: "Modern Urban Villa",
    location: "8 Beijing Road, Beijing, China",
    country: "China",
    specifications: {
      room: 6,
      bathRoom: 3,
      area: 2800,
      condition: true,
    },
  },
  {
    id: "de9174",
    name: "Countryside Cottage",
    location: "30 Forest Lane, Munich, Germany",
    country: "Germany",
    specifications: {
      room: 4,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "pk7240",
    name: "Suburban Family Home",
    location: "15 Green Street, Lahore, Pakistan",
    country: "Pakistan",
    specifications: {
      room: 5,
      bathRoom: 3,
      area: 2200,
      condition: true,
    },
  },
  {
    id: "in5369",
    name: "Vibrant City Condo",
    location: "25 Market Road, Mumbai, India",
    country: "India",
    specifications: {
      room: 2,
      bathRoom: 1,
      area: 800,
      condition: true,
    },
  },
  {
    id: "be8325",
    name: "Charming Townhouse",
    location: "10 Canal Street, Brussels, Belgium",
    country: "Belgium",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1200,
      condition: true,
    },
  },
  {
    id: "jp3197",
    name: "Traditional Ryokan",
    location: "5 Sakura Lane, Kyoto, Japan",
    country: "Japan",
    specifications: {
      room: 6,
      bathRoom: 4,
      area: 2500,
      condition: true,
    },
  },
  {
    id: "us6421",
    name: "Historic Brownstone",
    location: "30 Elm Street, Boston, USA",
    country: "United States",
    specifications: {
      room: 7,
      bathRoom: 4,
      area: 3000,
      condition: true,
    },
  },
  {
    id: "ca9265",
    name: "Scenic Mountain Lodge",
    location: "55 Summit Road, Vancouver, Canada",
    country: "Canada",
    specifications: {
      room: 3,
      bathRoom: 2,
      area: 1800,
      condition: false,
    },
  },
  {
    id: "it5784",
    name: "Elegant Villa",
    location: "8 Tuscan Avenue, Florence, Italy",
    country: "Italy",
    specifications: {
      room: 4,
      bathRoom: 3,
      area: 2000,
      condition: true,
    },
  },
];
